[workspace]
resolver = "3"
members = ["crates/*", "experimental"]

[workspace.package]
version = "0.2.4"
edition = "2024"
authors = ["Hyoung Joon, Kim"]
license = "MIT"
repository = "https://github.com/joonjoon0425/bake"

[workspace.dependencies]
bake-tabular = { path = "crates/bake-tabular" }
bake-deep = { path = "crates/bake-deep" }
bake-macros = { path = "crates/bake-macros" }
bake-common = { path = "crates/bake-common" }
burn = "0.22.0-pre.3"
rand = "0.10.2"