[workspace]
resolver = "3"
members = ["crates/*", "experimental"]

[workspace.dependencies]
bake-tabular = { path = "crates/bake-tabular", version = "1.0.0" }
bake-deep = { path = "crates/bake-deep", version = "0.2.0" }
bake-macros = { path = "crates/bake-macros", version = "0.1.0" }
bake-common = { path = "crates/bake-common", version = "0.1.0" }