[package]
name = "bake-rl-env"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bake-rl-core.workspace = true
burn = { workspace = true, optional = true }
rand.workspace = true

[dev-dependencies]
bake-rl-tabular.workspace = true

[features]
deep = ["dep:burn", "bake-rl-core/deep"]