[package]
name = "bake-rl-env-gym"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pyo3.workspace = true
numpy.workspace = true
rand.workspace = true
bake-rl-core.workspace = true

[build-dependencies]
pyo3-build-config = "0.29.2"
