[package]
name = "bake-rl-tabular"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bake-common.workspace = true
bake-rl-core.workspace = true
rand.workspace = true

[dev-dependencies]
bake = { workspace = true, features = ["rl-tabular"] }
bake-rl-env = { workspace = true }