[package]
name = "bake-rl-deep"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bake-common.workspace = true
bake-macros.workspace = true
bake-rl-core = { workspace = true, features = ["deep"] }

burn.workspace = true
rand.workspace = true
serde.workspace = true
toml.workspace = true