[package]
name = "bake"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bake-common.workspace = true
bake-rl = { workspace = true, default-features = false }

[features]
rl-tabular = ["bake-rl/tabular"]
rl-deep = ["bake-rl/deep"]
rl-gym = ["bake-rl/gym"]
rl-full = ["rl-tabular", "rl-deep", "rl-gym"]