[package]
name = "bake"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bake-tabular = { workspace = true, optional = true }
bake-deep = { workspace = true, optional = true }
bake-gym = { workspace = true, optional = true }
burn = { workspace = true, optional = true }
rand.workspace = true

[features]
default = ["tabular", "deep"]
tabular = ["dep:bake-tabular"]
deep = ["dep:bake-deep", "dep:burn"]
deep-gym = ["deep", "dep:burn", "dep:bake-gym"]
full = ["tabular", "deep-gym"]